apiVersion: apps/v1
kind: Deployment
metadata:
  name: dino
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dino
  template:
    metadata:
      labels:
        app: dino
    spec:
      containers:
      - name: dino
        image: plamencode/dino-game:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
