apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-quiz
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-quiz
  template:
    metadata:
      labels:
        app: dog-quiz
    spec:
      containers:
      - name: dog-quiz
        image: plamencode/dog-quiz:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
